# Week 1 - Iris Auto ML

Now let's look at this again, but using H2O's Auto ML feature.

In [1]:
import h2o

In [3]:
# check to see if H2O is running already and connect, or start it up
h2o.init(ip='h2o-service')

Checking whether there is an H2O instance running at http://h2o-service:54321 . connected.

--------------------------  ------------------------------------------------------------------
H2O_cluster_uptime:         1 min 27 secs
H2O_cluster_timezone:       Etc/UTC
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.32.0.4
H2O_cluster_version_age:    1 month and 17 days
H2O_cluster_name:           root
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    7.101 Gb
H2O_cluster_total_cores:    4
H2O_cluster_allowed_cores:  4
H2O_cluster_status:         accepting new members, healthy
H2O_connection_url:         http://h2o-service:54321
H2O_connection_proxy:       null
H2O_internal_security:      False
H2O_API_Extensions:         Amazon S3, XGBoost, Algos, AutoML, Core V3, TargetEncoder, Core V4
Python_version:             3.8.8 final
--------------------------  ------------------------------------------------------------------

In [4]:
# import the iris dataset
url = 'http://h2o-public-test-data.s3.amazonaws.com/smalldata/iris/iris_wheader.csv'
iris = h2o.import_file(url)

Parse progress: |█████████████████████████████████████████████████████████| 100%

In [5]:
# split the data into 80% train and 20% test
train, test = iris.split_frame([0.8])

In [6]:
# review a summary of our training data
train.summary()

,sepal_len,sepal_wid,petal_len,petal_wid,class
type,real,real,real,real,enum
mins,4.3,2.0,1.1,0.1,
mean,5.865322580645161,3.038709677419354,3.820967741935484,1.2137096774193548,
maxs,7.9,4.4,6.9,2.5,
sigma,0.8216624388326431,0.43124129352245405,1.7651216219893662,0.7575457460140347,
zeros,0,0,0,0,
missing,0,0,0,0,0
0,5.1,3.5,1.4,0.2,Iris-setosa
1,4.9,3.0,1.4,0.2,Iris-setosa
2,4.7,3.2,1.3,0.2,Iris-setosa
3,4.6,3.1,1.5,0.2,Iris-setosa
4,5.0,3.6,1.4,0.2,Iris-setosa
5,5.4,3.9,1.7,0.4,Iris-setosa
6,4.6,3.4,1.4,0.3,Iris-setosa
7,4.9,3.1,1.5,0.1,Iris-setosa
8,5.4,3.7,1.5,0.2,Iris-setosa
9,4.8,3.4,1.6,0.2,Iris-setosa

In [7]:
# how many rows in training - not exactly 80%
train.nrows

124

In [8]:
# how many rows in testing - not exactly 20%
test.nrows

26

In [9]:
# import auto ml
from h2o.automl import H2OAutoML

In [ ]:
# train the model
mA = H2OAutoML(max_runtime_secs=60)
mA.train(['sepal_len', 'sepal_wid', 'petal_len', 'petal_wid'], 'class', train)

AutoML progress: |███████████
09:02:22.228: Skipping training of model GBM_5_AutoML_20210319_090209 due to exception: water.exceptions.H2OModelBuilderIllegalArgumentException: Illegal argument(s) for GBM model: GBM_5_AutoML_20210319_090209.  Details: ERRR on field: _min_rows: The dataset size is too small to split for min_rows=100.0: must have at least 200.0 (weighted) rows, but have only 124.0.


██████████████████

In [10]:
# view the leader model
mA.leader

Model Details
=============
H2OGeneralizedLinearEstimator :  Generalized Linear Modeling
Model Key:  GLM_1_AutoML_20200209_195234


GLM Model: summary

,,family,link,regularization,lambda_search,number_of_predictors_total,number_of_active_predictors,number_of_iterations,training_frame
0,,multinomial,multinomial,Ridge ( lambda = 7.15E-5 ),"nlambda = 30, lambda.max = 44.404, lambda.min = 7.15E-5, lambda.1s...",15,12,191,automl_training_py_3_sid_83d2

ModelMetricsMultinomialGLM: glm
** Reported on train data. **

MSE: 0.004326081850443802
RMSE: 0.06577295683214951

ModelMetricsMultinomialGLM: glm
** Reported on cross-validation data. **

MSE: 0.013469083212128271
RMSE: 0.11605637945467828

Cross-Validation Metrics Summary:

,,mean,sd,cv_1_valid,cv_2_valid,cv_3_valid,cv_4_valid,cv_5_valid
0,accuracy,0.99130434,0.019444069,1.0,1.0,0.95652175,1.0,1.0
1,err,0.008695652,0.019444069,0.0,0.0,0.04347826,0.0,0.0
2,err_count,0.2,0.4472136,0.0,0.0,1.0,0.0,0.0
3,logloss,0.040125437,0.042201582,3.8147127E-4,0.015059838,0.10869362,0.028063606,0.048428655
4,max_per_class_error,0.025,0.0559017,0.0,0.0,0.125,0.0,0.0
5,mean_per_class_accuracy,0.9916667,0.0186339,1.0,1.0,0.9583333,1.0,1.0
6,mean_per_class_error,0.008333334,0.0186339,0.0,0.0,0.041666668,0.0,0.0
7,mse,0.011813632,0.014728339,5.3972985E-7,0.0016182398,0.036627512,0.008904781,0.011917091
8,null_deviance,50.061905,1.0143474,50.357388,50.53654,50.53654,50.623383,48.255672
9,r2,0.98217064,0.022696504,0.9999992,0.9975115,0.94367456,0.98719937,0.9824685
10,residual_deviance,1.8263987,1.9369872,0.017547678,0.69275254,4.9999065,1.2909259,2.1308608
11,rmse,0.087175146,0.07257863,7.346631E-4,0.04022735,0.19138315,0.09436515,0.10916543

Scoring History:

,,timestamp,duration,iteration,lambda,predictors,deviance_train,deviance_test,deviance_xval,deviance_se
0,,2020-02-09 19:52:43,0.000 sec,2,.44E2,15,2.150848,NaN,2.160953,0.002924
1,,2020-02-09 19:52:43,0.022 sec,4,.28E2,15,2.125808,NaN,2.140740,0.003550
2,,2020-02-09 19:52:43,0.049 sec,6,.17E2,15,2.087434,NaN,2.109373,0.004515
3,,2020-02-09 19:52:43,0.056 sec,8,.11E2,15,2.030258,NaN,2.061918,0.005987
4,,2020-02-09 19:52:43,0.070 sec,10,.66E1,15,1.948499,NaN,1.992616,0.008119
5,,2020-02-09 19:52:43,0.082 sec,12,.41E1,15,1.838454,NaN,1.896439,0.011011
6,,2020-02-09 19:52:43,0.101 sec,15,.25E1,15,1.700618,NaN,1.771865,0.014659
7,,2020-02-09 19:52:43,0.127 sec,18,.16E1,15,1.542807,NaN,1.622577,0.019027
8,,2020-02-09 19:52:43,0.144 sec,21,.98E0,15,1.376805,NaN,1.459813,0.023768
9,,2020-02-09 19:52:43,0.167 sec,24,.61E0,15,1.214921,NaN,1.295602,0.028890
10,,2020-02-09 19:52:43,0.193 sec,27,.38E0,15,1.066305,NaN,1.140962,0.034215
11,,2020-02-09 19:52:43,0.243 sec,30,.24E0,15,0.933976,NaN,1.002429,0.039264
12,,2020-02-09 19:52:43,0.296 sec,33,.15E0,15,0.816376,NaN,0.880045,0.043662
13,,2020-02-09 19:52:44,0.307 sec,36,.91E-1,15,0.707824,NaN,0.769974,0.046800
14,,2020-02-09 19:52:44,0.322 sec,39,.56E-1,15,0.604732,NaN,0.666665,0.048290
15,,2020-02-09 19:52:44,0.349 sec,42,.35E-1,15,0.507438,NaN,0.568115,0.047892
16,,2020-02-09 19:52:44,0.392 sec,46,.22E-1,15,0.417637,NaN,0.474985,0.046474
17,,2020-02-09 19:52:44,0.464 sec,51,.13E-1,15,0.339926,NaN,0.391941,0.044482
18,,2020-02-09 19:52:44,0.499 sec,56,.84E-2,15,0.275349,NaN,0.321414,0.042543
19,,2020-02-09 19:52:44,0.521 sec,62,.52E-2,15,0.222854,NaN,0.263535,0.040746

See the whole table with table.as_data_frame()

In [11]:
# predict on the test set
p = mA.leader.predict(test)

glm prediction progress: |████████████████████████████████████████████████| 100%

In [12]:
# review predictions
p

predict,Iris-setosa,Iris-versicolor,Iris-virginica
Iris-setosa,0.995562,0.00443822,5.27285e-26
Iris-setosa,0.999814,0.000185944,4.58444e-28
Iris-setosa,0.999954,4.61818e-05,2.29827e-28
Iris-setosa,0.999998,2.34739e-06,1.7193e-33
Iris-setosa,0.998537,0.00146288,4.59221e-29
Iris-setosa,0.999806,0.000193999,4.37153e-27
Iris-setosa,0.747049,0.252951,2.4273e-21
Iris-setosa,0.999973,2.65606e-05,2.0686e-27
Iris-setosa,0.99999,1.04211e-05,1.93e-30
Iris-versicolor,0.000121819,0.999804,7.40484e-05

In [13]:
# review model performance on the test set
mA.leader.model_performance(test)

ModelMetricsMultinomialGLM: glm
** Reported on test data. **

MSE: 0.04091297151480545
RMSE: 0.2022695516255609